from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.event_store.models import (
    ArticleMetadataRecord,
    EventRecord,
    LLMCallRecord,
    ToolCallRecord,
)


@runtime_checkable
class EventStore(Protocol):
    def record_event(self, event: EventRecord) -> None: ...
    def record_llm_call(self, record: LLMCallRecord) -> None: ...
    def record_tool_call(self, record: ToolCallRecord) -> None: ...
    def record_article_metadata(self, record: ArticleMetadataRecord) -> None: ...
    def query_llm_calls(self, session_id: str, run_id: str | None = None, limit: int = 100) -> list[LLMCallRecord]: ...
    def query_tool_calls(self, session_id: str, run_id: str | None = None, limit: int = 100) -> list[ToolCallRecord]: ...
    def close(self) -> None: ...
